version: "3"

networks:
  pva-network:
    driver: bridge

services:

  # ************************ MQTT **************************
  pva-mosquitto:
    image: md76/pva-mosquitto:${PVA_VERSION}-arm
    container_name: pva-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./resources/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - pva-network
    
  # ************************ ORCHESTRATOR **************************

  pva-orchestrator:
    image: md76/pva-orchestrator:${PVA_VERSION}-arm
    restart: always
    container_name: pva-orchestrator
    environment:
      - NODE_ENV=production
    networks:
      - pva-network
    depends_on:
      - pva-mosquitto

  # ************************ TTS **************************

  pva-tts:
    image: md76/pva-tts-mimic:${PVA_VERSION}-arm
    restart: always
    container_name: pva-tts
    devices:
      - /dev/snd:/dev/snd
    networks:
      - pva-network
    depends_on:
      - pva-mosquitto

  # ************************ CAPTURE SPEECH **************************

  pva-capture-speech:
    image: md76/pva-capture-speech:${PVA_VERSION}-arm
    restart: always
    container_name: pva-capture-speech
    devices:
      - /dev/snd:/dev/snd
    networks:
      - pva-network
    depends_on:
      - pva-mosquitto

  # ************************ HOTWORD **************************
    
  # pva-hotword:
  #   image: md76/pva-hotword-snowboy:${PVA_VERSION}-arm
  #   restart: always
  #   container_name: pva-hotword
  #   devices:
  #     - /dev/snd:/dev/snd
  #   networks:
  #     - pva-network
  #   volumes:
  #     - ./resources/snowboy/models/Hotword.pmdl:/usr/src/app/models/Hotword.pmdl
  #   depends_on:
  #     - pva-mosquitto

  # pva-hotword:
  #   image: md76/pva-hotword-porcupine:${PVA_VERSION}-arm
  #   restart: always
  #   container_name: pva-hotword
  #   environment:
  #     - SYSTEM_HOTWORDS=grapefruit,grasshopper
  #   devices:
  #     - /dev/snd:/dev/snd
  #   networks:
  #     - pva-network
  #   depends_on:
  #     - pva-mosquitto

  # ************************ STT **************************

  # pva-stt:
  #   image: md76/pva-stt-wit:${PVA_VERSION}-arm
  #   restart: always
  #   container_name: pva-stt
  #   # environment:
  #   #   - STT_ALT=1
  #   volumes:
  #     - ./resources/wit/key.txt:/usr/src/app/key.txt
  #   networks:
  #     - pva-network
  #   depends_on:
  #     - pva-mosquitto

  # pva-stt:
  #   image: md76/pva-stt-pocketsphinx:${PVA_VERSION}-arm
  #   restart: always
  #   container_name: pva-stt
  #   environment:
  #     - PSX_LANGUAGE_PATH=model/en-us
  #     - PSX_HMM_PATH=model/en-us/en-us
  #     - PSX_LM_FILE=model/en-us/en-us.lm.bin
  #     - PSX_DICT_FILE=model/en-us/cmudict-en-us.dict
  #   #   - STT_ALT=1
  #   volumes:
  #     - ./resources/pocketsphinx/model:/usr/src/app/model
  #   networks:
  #     - pva-network
  #   depends_on:
  #     - pva-mosquitto

  # pva-stt:
  #   image: md76/pva-stt-google:${PVA_VERSION}-arm
  #   restart: always
  #   container_name: pva-stt
  #   # environment:
  #   #   - STT_ALT=1
  #   volumes:
  #     - ./resources/google/credentials.json:/usr/src/app/credentials.json
  #   networks:
  #     - pva-network
  #   depends_on:
  #     - pva-mosquitto

  
  # ************************ NLU **************************
  
  # pva-nlu:
  #   image: md76/pva-nlu-light:${PVA_VERSION}-arm
  #   restart: always
  #   container_name: pva-nlu
  #   networks:
  #     - pva-network
  #   volumes:
  #     - ./resources/nlu/models:/usr/src/app/models
  #     - ./resources/nlu/training_data/<YOUR TRAINING YAML FILE>:/usr/src/app/training_data/train.yaml
  #   environment:
  #     - LANGUAGE=en
  #   depends_on:
  #     - pva-mosquitto

  # pva-nlu:
  #   image: md76/pva-nlu-spacy:${PVA_VERSION}-en-sm-arm
  #   restart: always
  #   container_name: pva-nlu
  #   networks:
  #     - pva-network
  #   volumes:
  #     - ./resources/nlu/models:/usr/src/app/models
  #   environment:
  #     - LANGUAGE=en
  #     - SPACY_MODEL=en_core_web_sm
  #   depends_on:
  #     - pva-mosquitto