version: "3"

networks:
  yava-network:
    driver: bridge

services:

  # ************************ MQTT **************************
  yava-mosquitto:
    image: md76/yava-mosquitto:${YAVA_VERSION}-arm
    container_name: yava-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./resources/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - yava-network
    
  # ************************ ORCHESTRATOR **************************

  yava-orchestrator:
    image: md76/yava-orchestrator:${YAVA_VERSION}-arm
    restart: always
    container_name: yava-orchestrator
    environment:
      - NODE_ENV=production
    networks:
      - yava-network
    depends_on:
      - yava-mosquitto

  # ************************ TTS **************************

  yava-tts:
    image: md76/yava-tts-mimic:${YAVA_VERSION}-arm
    restart: always
    container_name: yava-tts
    devices:
      - /dev/snd:/dev/snd
    networks:
      - yava-network
    depends_on:
      - yava-orchestrator

  # ************************ CAPTURE SPEECH **************************

  yava-capture-speech:
    image: md76/yava-capture-speech:${YAVA_VERSION}-arm
    restart: always
    container_name: yava-capture-speech
    devices:
      - /dev/snd:/dev/snd
    networks:
      - yava-network
    depends_on:
      - yava-orchestrator

  # ************************ HOTWORD **************************
    
  # yava-hotword:
  #   image: md76/yava-hotword-snowboy:${YAVA_VERSION}-arm
  #   restart: always
  #   container_name: yava-hotword
  #   devices:
  #     - /dev/snd:/dev/snd
  #   networks:
  #     - yava-network
  #   volumes:
  #     - ./resources/snowboy/models/Hotword.pmdl:/usr/src/app/models/Hotword.pmdl
  #   depends_on:
  #     - yava-orchestrator

  # yava-hotword:
  #   image: md76/yava-hotword-porcupine:${YAVA_VERSION}-arm
  #   restart: always
  #   container_name: yava-hotword
  #   environment:
  #     - SYSTEM_HOTWORDS=grapefruit,grasshopper
  #   devices:
  #     - /dev/snd:/dev/snd
  #   networks:
  #     - yava-network
  #   depends_on:
  #     - yava-orchestrator

  # ************************ STT **************************

  # yava-stt:
  #   image: md76/yava-stt-wit:${YAVA_VERSION}-arm
  #   restart: always
  #   container_name: yava-stt
  #   # environment:
  #   #   - STT_ALT=1
  #   volumes:
  #     - ./resources/wit/key.txt:/usr/src/app/key.txt
  #   networks:
  #     - yava-network
  #   depends_on:
  #     - yava-orchestrator

  # yava-stt:
  #   image: md76/yava-stt-pocketsphinx:${YAVA_VERSION}-arm
  #   restart: always
  #   container_name: yava-stt
  #   environment:
  #     - PSX_LANGUAGE_PATH=model/en-us
  #     - PSX_HMM_PATH=model/en-us/en-us
  #     - PSX_LM_FILE=model/en-us/en-us.lm.bin
  #     - PSX_DICT_FILE=model/en-us/cmudict-en-us.dict
  #   #   - STT_ALT=1
  #   volumes:
  #     - ./resources/pocketsphinx/model:/usr/src/app/model
  #   networks:
  #     - yava-network
  #   depends_on:
  #     - yava-orchestrator

  # yava-stt:
  #   image: md76/yava-stt-google:${YAVA_VERSION}-arm
  #   restart: always
  #   container_name: yava-stt
  #   # environment:
  #   #   - STT_ALT=1
  #   volumes:
  #     - ./resources/google/credentials.json:/usr/src/app/credentials.json
  #   networks:
  #     - yava-network
  #   depends_on:
  #     - yava-orchestrator

  
  # ************************ NLU **************************
  
  # yava-nlu:
  #   image: md76/yava-nlu-light:${YAVA_VERSION}-arm
  #   restart: always
  #   container_name: yava-nlu
  #   networks:
  #     - yava-network
  #   volumes:
  #     - ./resources/nlu/models:/usr/src/app/models
  #     - ./resources/nlu/training_data/<YOUR TRAINING YAML FILE>:/usr/src/app/training_data/train.yaml
  #   environment:
  #     - LANGUAGE=en
  #   depends_on:
  #     - yava-orchestrator

  # yava-nlu:
  #   image: md76/yava-nlu-spacy:${YAVA_VERSION}-en-sm-arm
  #   restart: always
  #   container_name: yava-nlu
  #   networks:
  #     - yava-network
  #   volumes:
  #     - ./resources/nlu/models:/usr/src/app/models
  #   environment:
  #     - LANGUAGE=en
  #     - SPACY_MODEL=en_core_web_sm
  #   depends_on:
  #     - yava-orchestrator